---
version: "2.1"
services:
    plex:
        image: ghcr.io/linuxserver/plex
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=latest
        volumes:
            - /home/plex/config:/config
            - /home/shared/Media:/data
            - /home/plex/transcode:/transcode
        restart: unless-stopped
