---
version: "2.1"
services:
    plex:
        image: lscr.io/linuxserver/plex
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=latest
        volumes:
            - /home/plex/config:/config
            - /disks/disk1:/disk1
            - /disks/disk2:/disk2
            - /disks/disk3:/disk3
            - /disks/disk4:/disk4
        devices:
            - /dev/dri:/dev/dri
        restart: unless-stopped
